### ISSUE TITLE
Link to API docs is broken 

### ISSUE THREAD

**Issue by jcpsantiago** [bostonaholic/ring-okta#12]
Hey thanks for this! I just found your library and will now try to use it to add Okta to my app. I noticed the link to the API docs is broken, although the html is there. Some issue with github pages? Thought i would let you know :)

**Comment by bostonaholic** [comment]
Thank you for letting me know! It should be fixed now.

I think it happened when I changed the default branch from `master` to `main`. GitHub must have turned off the GitHub Pages setting instead of migrating the setting to point to the new default branch.
