### ISSUE TITLE
Allow okta-config to be present outside the bundled jar

### ISSUE THREAD

**Issue by ravik-karn-tw** [bostonaholic/ring-okta#3]
In the older version of library the okta-config could be taken from any path but after https://github.com/bostonaholic/ring-okta/commit/ac67d77dec12e46c42cd24541e9f9f3e0a5ee861 commit it is expected to be in resource folder. Which is restricting us to build one jar and use it across multiple environment. 

Is there any alternative to bundle the jar and reuse across multiple environment?

**Comment by ravik-karn-tw** [comment]
https://github.com/bostonaholic/ring-okta/pull/4

Hope this PR solves it

**Comment by bostonaholic** [comment]
Closed by #4
